### ISSUE TITLE
falco-exporter: Add PSP, Role and RoleBinding Helm templates to the chart

### ISSUE THREAD

**Issue by PhilipSchmid** [falcosecurity/charts#103]
Hi there,

**Motivation**

I'm currently working in a quite restrictive K8s environment and unfortunately wasn't able to deploy falco-exporter until now since the falco-exporter Helm chart only comes with a [ServiceAccount "falco-exporter"](https://github.com/falcosecurity/charts/blob/master/falco-exporter/templates/serviceaccount.yaml) but without any configuration about the required PSP privileges.

**Feature**

Since the falco-exporter DaemonSet uses a `hostPath` volume (see https://github.com/falcosecurity/charts/blob/master/falco-exporter/templates/daemonset.yaml#L64-L67) it's sometimes required to explicitly allow this behavior via separate PSP, ClusterRole & ClusterRoleBinding.

A possible PSP probably could look like this:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: falco-exporter
  name: falco-exporter
spec:
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - 'hostPath'
  allowedHostPaths:
  - pathPrefix: "/var/run/falco"
    readOnly: true
```

But what's with the ClusterRole? I mean which permissions need to be configured inside it? Since falco-exporter is able to add a ServiceMonitor and/or a Grafana Dashboard ConfigMap I don't think something like to following will be sufficient:

```yaml
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: falco-exporter
  labels:
    app: falco-exporter
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - falco-exporter
    verbs:
      - use
... what else here?
```

If you can tell me the exactly required ClusterRole permissions I could implement this change via PR (if you want)..

Thanks!

Regards,
Philip

**Comment by leogr** [comment]
Hey,

good questions. TBH, I have not found the time to dig into that, anyways:
- falco-exporter really needs just the `hostPath` to work properly
- falco-exporter does not add a ServiceMonitor and/or a Grafana Dashboard ConfigMap, the helm chart does that on installation 
- the Grafana Dashboard ConfigMap is not used by falco-exporter itself, Grafana should consume it
- same for the ServiceMonitor, it describes the target to be monitored by Prometheus
- finally, the pod exposes a service and annotations (that can be configured [here](https://github.com/falcosecurity/charts/blob/master/falco-exporter/values.yaml#L5)) consumed by Prometheus

Thus, if I didn't forget anything, the PSP and ClusterRole examples may be already complete.

WDYT?

**Comment by PhilipSchmid** [comment]
Hi @leogr,

Ahright, of course 💡! Helm deploys the Grafana and ServiceMonitor stuff so the ServiceAccount does not need this privileges. I was able to bring falco-exporter UP using the following objects:

```yaml
---
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  labels:
    app: falco-exporter
  name: falco-exporter
spec:
  allowPrivilegeEscalation: true
  allowedHostPaths:
  - pathPrefix: /var/run/falco
    readOnly: true
  fsGroup:
    rule: RunAsAny
  runAsUser:
    rule: RunAsAny
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: RunAsAny
  volumes:
  - hostPath
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: falco-exporter
  labels:
    app: falco-exporter
rules:
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - falco-exporter
    verbs:
      - use
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: falco-exporter
  labels:
    app: falco-exporter
subjects:
  - kind: ServiceAccount
    name: falco-exporter
    namespace: <falco-exporter-ns-here>
roleRef:
  kind: ClusterRole
  name: falco-exporter
  apiGroup: rbac.authorization.k8s.io
```

If you want I could add these to the templates and create a PR within the nest few days. Would you be interested in this? 

Thanks!

Regards,
Philip
