### ISSUE TITLE
falco-exporter: Using imagePullSecrets conflicts with PSP

### ISSUE THREAD

**Issue by PhilipSchmid** [falcosecurity/charts#115]
**Describe the bug**

The usage of imagePullSecrets is currently not working with the falco-exporter default PSP which only allows volumes of type `hostPath`. https://github.com/falcosecurity/charts/blob/0e32bbeb66b2781842e6829e0ba69980dd18e7de/falco-exporter/templates/podsecuritypolicy.yaml#L26

Example:

A Falco-Exporter values file with the following config ...
```yaml
...
imagePullSecrets:
- name: my-awesome-image-pull-secret
...
```
... is not able to run ...
```bash
$ kubectl describe ds -n falco falco-exporter
...
  Warning  FailedCreate      77s (x10 over 18m)  daemonset-controller  Error creating: pods "falco-exporter-" is forbidden: unable to validate against any pod security policy: [spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "secret": secret volumes are not allowed to be used]
```

**Additional context**

This bug was introduced with falco-exporter chart version `0.3.5`. https://github.com/falcosecurity/charts/pull/114 chose the PSP too restrictive. We need to add `secret` too:

```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  ...
  name: falco-exporter
spec:
  ...
  volumes:
  - hostPath
  - secret
```

@leogr: I'll open a PR in a few hours which will fix this issue.

Regards,
Philip

**Comment by leogr** [comment]
Good catch, thank you. I did not consider that. Have you checked for other similar issues yet?

**Comment by PhilipSchmid** [comment]
Otherwise it runs as excepted with the following Helm values configuration:

```yaml
image:
  repository: <hidden>
  tag: 0.3.0
imagePullSecrets:
- name: my-awesome-image-pull-secret
podSecurityPolicy:
  create: true
serviceMonitor:
  enabled: true
  additionalLabels:
    release: <hidden>
grafanaDashboard:
  enabled: true
  namespace: <hidden>
``` 

Regards,
Philip
