### ISSUE TITLE
Deprecate Falco's chart integrations in favor of falcosidekick

### ISSUE THREAD

**Issue by leogr** [falcosecurity/charts#123]
**Motivation**

Falco's chart comes with various [thirdy-party integrations](https://github.com/falcosecurity/charts/blob/master/falco/values.yaml#L283-L334) that seems to be not maintained anymore.

Moreover, the current implementation of those integrations relies on several docker images that live outside the falcosecurity org:
https://github.com/falcosecurity/charts/blob/524dcbce776c8696ac2355242f233c3a11ae2653/falco/templates/daemonset.yaml#L147, https://github.com/falcosecurity/charts/blob/524dcbce776c8696ac2355242f233c3a11ae2653/falco/templates/daemonset.yaml#L156, https://github.com/falcosecurity/charts/blob/524dcbce776c8696ac2355242f233c3a11ae2653/falco/templates/daemonset.yaml#L181

That makes Falco's chart hard to maintain Falco's chart too ([here](https://github.com/falcosecurity/charts/pull/55) is an example).

Finally, falcosidekick (that's actively maintained, lives inside the falcosecurity org, and its chart is already inside this repository) already provides some of those integrations (missing ones are coming soon). 

**Feature**

Remove the following integrations from the Falco's chart:
- `gcscc` (i.e., Google Cloud Security Command Center)
- `natsOutput` 
- `snsOutput`
- `pubsubOutput` (i.e., Google Cloud Pub/Sub)

Finally, document how Falco's chart can integrate with those services by using falcosidekick's. 

**Alternatives**

Do nothing. But sooner or later the current integrations will not work anymore. 

**Additional context**

Service supported by falcosidekick:
- [x] NATS
- [x] SNS (recently added)
- [x] PubSub (work already in progress)
- [ ] GCloud Security Command Center

Slack channel discussion :point_down: 
https://kubernetes.slack.com/archives/CMWH3EH32/p1602690485207200

cc @Issif @nibalizer

**Comment by leogr** [comment]
cc'ing folks that might be using those integrations:
@fjudith @dza89 @NingPekin

**Comment by nibalizer** [comment]
I greatly agree, we can better support these kinds of things in the sidekick. I'd even say we should default the http output option to `http://falco-sidekick:2801` or similar.

**Comment by Issif** [comment]
I even thought about integrating falcosidekick in falco's chart, as a dependency, what do you think about?

**Comment by nibalizer** [comment]
I'm not sure. I would like a single entry point for users. However I feel that bloated code and tons of options doesn't serve the users well. Separation is good, however Helm doesn't seem to have the best tooling to support collections of charts working together.

I found these two things:

* https://github.com/roboll/helmfile
* https://helm.sh/docs/chart_best_practices/dependencies/

Neither of which really looks all that great. It does seem like we could use 


```
condition: falcosidekick.enabled
```

inside the main Falco chart to turn on http output to port 2801. That might be confusing for the users if http output is disabled in their values.yaml but enabled after they apply the chart.

I'm not against folding the sidekick chart into the main falco chart, I just worry that we're replacing one extension with another, and that in the future we'll probably be shy to change defaults in the falco chart and more willing to iterate and be disruptive to users in a separate chart.

**Comment by Issif** [comment]
I agree. I just wondered if we could just enable the import of falcosidekick"s chart with a boolean, but it doesn't seem possible with helm. When all will be ready in falcosidekick, its chart and this. I will write the relative documentation.

**Comment by Issif** [comment]
For `GCloud Security Command Center`, I checked the current implementation, it's just a simple curl. The `webhook` output in falcosidekick will work, it only needs a way to specify the `Authorization Token` as header, and this is possible since tonight, in that branch : https://github.com/falcosecurity/falcosidekick/tree/authorization-header.

After implementation of `PubSub`, falcosidekick will be fully able to replace these components.

**Comment by leogr** [comment]
Hey

I would like to introduce a deprecation notice in the Falco chart right now. WDYT?

**Comment by Issif** [comment]
@leogr It could be add in `_helpers.tpl`, I agree.

**Comment by leogr** [comment]
Update:
I believe the only missing piece now is the GCloud Security Command Center. So I'm starting to clean up the chart at this point.

**Comment by AbirHamzi** [comment]
Hello everyone, is it possible to introduce a readiness probe in falco to check that falcosidekick is available (when enabled ofc ) something like this maybe : 
```
    readinessProbe:
      tcpSocket:
        host: falcosidekick
        port: 2801
```

**Comment by Issif** [comment]
Hi @AbirHamzi,

For me, it's not the duty of `falco` to check if its backends are up and running. For the moment, `falcosidekick` is the "official" output extender but it may change in future if someone brings a better tool. We should not intricate them.

In kubernetes, `falcosidekick` deployment already has `readiness` and `liveness` probes:

```yaml
          livenessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /ping
              port: http
            initialDelaySeconds: 10
            periodSeconds: 5
```
And when you set in `falco`'s config: 

```yaml
httpOutput:
  enabled: true
  url: "http://falcosidekick:2801/"
```

You use a `kubernetes` service that uses these probes.

**Comment by AbirHamzi** [comment]
@Issif okay if you see so, but just to clarify my point of view, I meant that from falco side if we enable the http output (for falcosidekick or any other server) we may set unreachable url by mistake (I did that :() we can see that in falco logs but I thought it's better to introduce it as readiness probe to save debugging time and we read values from values.yaml like following:

```
   readinessProbe:
      tcpSocket:
        host: {{ .Values.httpOutput.host }}
        port: {{ .Values.httpOutput.port }}
```
