### ISSUE TITLE
Helm Template for falco webserver service nodeport issue

### ISSUE THREAD

**Issue by david-freistrom** [falcosecurity/charts#206]
**Describe the bug**

The nodePort variable for the integrated Webserver is used twice with different expected datatypes.
In the values.yml it is expected as a boolean for conditional template part.
But the nodePort itself is used also in the same template to define the nodePort statically expected as an integer.

**How to reproduce it**

Enable Webserver and AuditLogs and set nodePort to true in the values.yml

**Expected behaviour**

Deploy a Kubernetes service for the integrated webserver with an random nodePort

**Screenshots**

```yaml
spec:
  {{- if .Values.falco.webserver.nodePort }}
  type: NodePort
  {{- end }}
  selector:
    app: {{ template "falco.fullname" .}}
  ports:
  - protocol: TCP
    port: {{ .Values.falco.webserver.listenPort }}
    {{- with .Values.falco.webserver.nodePort }}
    nodePort: {{ . }}
    {{- end }}
{{- end }}
```

**Environment**

- Falco version:
Falco version: 0.27.0
Driver version: 5c0b863ddade7a45568c0ac97d037422c9efb750

- System info:
Sat Mar 27 00:59:59 2021: Falco version 0.27.0 (driver version 5c0b863ddade7a45568c0ac97d037422c9efb750)
Sat Mar 27 00:59:59 2021: Falco initialized with configuration file /etc/falco/falco.yaml
Sat Mar 27 00:59:59 2021: Loading rules from file /etc/falco/falco_rules.yaml:
Sat Mar 27 01:00:01 2021: Loading rules from file /etc/falco/falco_rules.local.yaml:
{
  "machine": "x86_64",
  "nodename": "falco-qhqw2",
  "release": "4.18.0-240.15.1.el8_3.x86_64",
  "sysname": "Linux",
  "version": "#1 SMP Mon Mar 1 17:16:16 UTC 2021"
}

- Cloud provider or hardware configuration:
Kubernetes OnPrem VServer

- OS:
NAME="CentOS Linux"
VERSION="8"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="8"
PLATFORM_ID="platform:el8"
PRETTY_NAME="CentOS Linux 8"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:8"
HOME_URL="https://centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"
CENTOS_MANTISBT_PROJECT="CentOS-8"
CENTOS_MANTISBT_PROJECT_VERSION="8"

- Kernel:
Linux worker01 4.18.0-240.15.1.el8_3.x86_64 #1 SMP Mon Mar 1 17:16:16 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

- Installation method:
helm install falco falcosecurity/falco -f values.yml

**Additional context**
