### ISSUE TITLE
liveness probe error

### ISSUE THREAD

**Issue by rodriguez-facundo** [falcosecurity/charts#235]
Noticed after yesterday's update, our deployment started to fail liveness probe

```
Liveness probe errored: strconv.Atoi: parsing "http": invalid syntax
```

I'll fix my end, but dropping the comment here just in case :) 

this is the deployment

```yaml
  values:
    image:
      tag: 0.28.1
    tolerations:
       ....

    falco:
      jsonOutput: true
      jsonIncludeOutputProperty: true
      httpOutput:
        enabled: true
        url: "http://falcosidekick.falco.svc.cluster.local:2801/"

      grpc:
        enabled: true

    customRules:
      rules-skips.yaml: |-
        - macro: user_known_write_below_etc_activities
          condition: ....

    falcosidekick:
      enabled: true
      config:
        slack:
          outputformat: fields
          minimumpriority: error
          webhookurl:  ....
```
