### ISSUE TITLE
ClusterRoleBinding missing for falcosidekick

### ISSUE THREAD

**Issue by philipsparrow** [falcosecurity/charts#275]
**Describe the bug**

When deploying chart `falco` with PSP creation, falcosidekick is missing the ClusterRoleBinding.
As a result, falcosidekick pods cannot be created.

**How to reproduce it**

values.yaml
```
podSecurityPolicy:
  create: true
falcosidekick:
  enabled: true
  podSecurityPolicy:
    create: true
```
```
helm repo add falcosecurity https://falcosecurity.github.io/charts
helm repo update
helm upgrade --install falco -f values.yaml falcosecurity/falco --version 1.15.7 --create-namespace --namespace falco
```

**Expected behaviour**

```
kubectl --namespace=falco get deploy       
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
falco-falcosidekick   2/2     2            2           37m
```

**Screenshots**

```
kubectl --namespace=falco get deploy       
NAME                  READY   UP-TO-DATE   AVAILABLE   AGE
falco-falcosidekick   0/2     0            0           37m
```

```
kubectl --namespace=falco describe rs
Name:           falco-falcosidekick-b898dd4b4
Namespace:      falco
Selector:       app.kubernetes.io/instance=falco,app.kubernetes.io/name=falcosidekick,pod-template-hash=b898dd4b4
Labels:         app.kubernetes.io/instance=falco
                app.kubernetes.io/name=falcosidekick
                pod-template-hash=b898dd4b4
Annotations:    deployment.kubernetes.io/desired-replicas: 2
                deployment.kubernetes.io/max-replicas: 3
                deployment.kubernetes.io/revision: 1
                meta.helm.sh/release-name: falco
                meta.helm.sh/release-namespace: falco
Controlled By:  Deployment/falco-falcosidekick
Replicas:       0 current / 2 desired
Pods Status:    0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/instance=falco
                    app.kubernetes.io/name=falcosidekick
                    pod-template-hash=b898dd4b4
  Annotations:      checksum/config: e8cbd615e67d235a372ce8ac6d6cef888c193cc10adea59d49dbe0ad6f99399b
  Service Account:  falco-falcosidekick
  Containers:
   falcosidekick:
    Image:      docker.io/falcosecurity/falcosidekick:2.23.1
    Port:       2801/TCP
    Host Port:  0/TCP
    Liveness:   http-get http://:http/ping delay=10s timeout=1s period=5s #success=1 #failure=3
    Readiness:  http-get http://:http/ping delay=10s timeout=1s period=5s #success=1 #failure=3
    Environment Variables from:
      falco-falcosidekick  Secret  Optional: false
    Environment:
      DEBUG:               false
      CUSTOMFIELDS:        
      MUTUALTLSFILESPATH:  /etc/certs
    Mounts:                <none>
  Volumes:                 <none>
Conditions:
  Type             Status  Reason
  ----             ------  ------
  ReplicaFailure   True    FailedCreate
Events:
  Type     Reason        Age                   From                   Message
  ----     ------        ----                  ----                   -------
  Warning  FailedCreate  54s (x15 over 2m16s)  replicaset-controller  Error creating: pods "falco-falcosidekick-b898dd4b4-" is forbidden: PodSecurityPolicy: unable to admit pod: []
```

**Environment**

GKE (1.19) with PSPs enabled.

Chart version:
1.15.7
- Installation method:
Helm3

**Additional context**

I worked-around the issue by applying the following manifest to the cluster:
```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: falco-falcosidekick
  name: falco-falcosidekick
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: falco-falcosidekick
subjects:
- kind: ServiceAccount
  name: falco-falcosidekick
  namespace: falco
```
I see that the file `falco/templates/clusterrolebinding.yaml` exists, but `falcosidekick/templates/clusterrolebinding.yaml` does not exist.

Looks like it was missed in https://github.com/falcosecurity/charts/pull/111 when addressing issue https://github.com/falcosecurity/charts/issues/110
