### ISSUE TITLE
falco create wrong ingress version for falcosidekick

### ISSUE THREAD

**Issue by devopstales** [falcosecurity/charts#288]
**Describe the bug**
falco create wrong ingress version for falcosidekick:

```
Error: UPGRADE FAILED: unable to recognize "": no matches for kind "Ingress" in version "networking.k8s.io/v1beta1"
```

**How to reproduce it**
Install falco from https://falcosecurity.github.io/charts with values:

```
    podSecurityPolicy:
      create: true
    ebpf:
      enabled: false
    auditLog:
      enabled: true
    falco:
      grpc:
        enabled: true
      grpcOutput:
        enabled: true
      webserver:
        enabled: true
    falcosidekick:
      enabled: true
      fullfqdn: true
      webui:
        enabled: true
      # for configuration values, see https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
          cert-manager.io/cluster-issuer: ca-issuer
          nginx.ingress.kubernetes.io/auth-url: "http://auth-proxy-oauth2-proxy.ingress-system.svc.cluster.local/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://oauth.k8s.intra/oauth2/start?rd=https%3A%2F%2F$host$request_uri"
        hosts:
          - host: falco.k8s.intra
            paths:
              - path: /
                pathType: Prefix
        tls:
          - secretName: falco-ingress-tls
            hosts:
            - falco.k8s.intra
```
**Expected behaviour**
Falco creates ingress with api version `networking.k8s.io/v1`

**Environment**

- Falco version:  0.30.0
- System info:
- OS: almalinux 8
- Kernel: `Linux alma8 4.18.0-305.10.2.el8_4.x86_64 #1 SMP Thu Jul 22 07:08:07 EDT 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Installation method: RPM and helm
- kubernetes version: v1.22.2

**Additional context**
