### ISSUE TITLE
Adding Exceptions

### ISSUE THREAD

**Issue by keefbaker** [falcosecurity/charts#327]
I can't see a way to add exceptions to rules in the chart. Is there a way to do this?

**Comment by keefbaker** [comment]
I added them by copying the rule from the configmap into the customRules section with an added exception and it worked

**Comment by kstavropoulos-fl** [comment]
@keefbaker can you please show an example of what you did?

**Comment by keefbaker** [comment]
Unfortunately I don't have access to that code any more as I've left that organization. But you examine the config file in the config map, add that rule verbatim into the customRules in the helm chart under exceptions.yaml (see the example about 2 thirds down here https://github.com/falcosecurity/charts/blob/master/falco/README.md) and put the exceptions in the format described here https://falco.org/docs/rules/exceptions/. It'll overrride the default rule and your exceptions will be in place.

**Comment by keefbaker** [comment]
Pretty sure the configmap is just called falco.

**Comment by kstavropoulos-fl** [comment]
Thanks :) I managed to make it work after -of course- reading the docs more, and attempting a few stupid things...
For the record, here is what I have (my use-case is excluding an alert for `writing under /etc` that is triggered by datadog-agent):
```
extraVolumes:
- name: custom-rules-volume
  configMap:
    name: falco-rules
    optional: true
    items:
    - key: falco_rules.custom.yaml
      path: falco_rules.custom.yaml

extraVolumeMounts:
- mountPath: /etc/falco/rules.custom.d
  name: custom-rules-volume

customRules:
  falco_rules.custom.yaml: |-
    - rule: Write below etc
      desc: an attempt to write to any file below /etc
      condition: write_etc_common
      exceptions:
      - name: new_datadog_pod
        fields: [container.image.repository, k8s.ns.name, fd.name, proc.cmdline]
        comps: [=, =, =, =]
        values:
        - [public.ecr.aws/datadog/agent, datadog, /etc/datadog-agent/auth_token, agent run]
      output: "File below /etc opened for writing (user=%user.name user_loginuid=%user.loginuid command=%proc.cmdline parent=%proc.pname pcmdline=%proc.pcmdline file=%fd.name program=%proc.name gparent=%proc.aname[2] ggparent=%proc.aname[3] gggparent=%proc.aname[4] container_id=%container.id image=%container.image.repository)"
      priority: ERROR
      tags: [filesystem, mitre_persistence]
      append: false

falco:
  rulesFile:
  - /etc/falco/falco_rules.yaml
  - /etc/falco/falco_rules.local.yaml
  - /etc/falco/rules.d
  - /etc/falco/rules.custom.d
```
