### ISSUE TITLE
Simplify driver-loader init container usage for users

### ISSUE THREAD

**Issue by PierreBart** [falcosecurity/charts#339]
**Motivation**

I am using your Helm chart with the driver-loader init container. I would have preferred to have the init container part of the template with most of the attributes already set instead of filling the extraInitContainers with the required values, i.e:
```yaml
image:
  repository: falcosecurity/falco-no-driver

extraInitContainers:
  - name: driver-loader
    image: docker.io/falcosecurity/falco-driver-loader:latest
    imagePullPolicy: Always
    volumeMounts:
      - mountPath: /host/proc
        name: proc-fs
        readOnly: true
      - mountPath: /host/boot
        name: boot-fs
        readOnly: true
      - mountPath: /host/lib/modules
        name: lib-modules
      - mountPath: /host/usr
        name: usr-fs
        readOnly: true
      - mountPath: /host/etc
        name: etc-fs
        readOnly: true
      - mountPath: /root/.falco
        name: driver-fs
    env:
      - name: FALCO_BPF_PROBE
        value:

extraVolumes:
  - name: driver-fs
    emptyDir: {}

extraVolumeMounts:
  - mountPath: /root/.falco
    name: driver-fs

ebpf:
  enabled: true

```

That way I would not have to worry about the volumes mounts or other changes for the forthcoming chart releases.

**Feature**

Add the driver-loader init container fields inside the daemonset template and enable it with a simple feature flag like:
```yaml
driverLoader:
  enabled: true
  image:
    registry: docker.io
    repository: falcosecurity/falco-driver-loader
    tag: 0.31.1
    pullPolicy: IfNotPresent
    
# Still, there is the need to set the Falco container pod:
image:
  repository: falcosecurity/falco-no-driver
```
