### ISSUE TITLE
Undefined macro X used in filter

### ISSUE THREAD

**Issue by dadav** [falcosecurity/charts#343]
**Describe the bug**

I'm trying to use the following **customRules**:

```yaml
customRules:
  falco_rules.local.yaml: |-
    - macro: user_known_write_below_binary_dir_activities
      condition: (openshift_image or container.image.repository in (trusted_images))
```

but the pods are crashing with the following error:

```shell
Compilation error when compiling "(openshift_image or container.image.repository in (dadav/falco))": Undefined macro 'openshift_image' used in filter.
---
- macro: user_known_write_below_binary_dir_activities
condition: (openshift_image or container.image.repository in (trusted_images))
---
. Exiting.
```

BUT the macro `openshift_image` is a default macro and therefore I expected it to be usable in this scope.

 **How to reproduce it**

Use a default macro in a condition field via the **customRules** parameter.

**Expected behaviour**

I expect the default macro to be usable in another condition.

**Environment**

- Falco version: 0.31.1
- System info: I deployed falco with this helm chart (version: falco-1.18.5) in openshift (I can't run the support command because the pods are crashing)
- Cloud provider or hardware configuration: OpenShift 4.10
