### ISSUE TITLE
Elasticsearch integration logs for falcosidekick

### ISSUE THREAD

**Issue by SanaZulfiqar73** [falcosecurity/charts#348]
Hi,

I integrated Elasticsearch as a sidekick. The configuration is like that:

```
elasticsearch:
    hostport: "http://opensearch-cluster.local:9200"
    index: "falco"
    type: "event"
    suffix: "daily"
    minimumpriority: "debug"
    mutualtls: false
    checkcert: true
    username: ""
    password: ""
```
 How can I verify if it is integrated successfully?

I don't see anything in the logs. Not even any error related to that. And, I can't see new index created in Elasticsearch as well.
