### ISSUE TITLE
ElasticSearch giving unknown missing header error

### ISSUE THREAD

**Issue by SanaZulfiqar73** [falcosecurity/charts#371]
**Describe the bug**

I am configuring OpenSearch as a falcosidekick to send the falco logs. Sometimes it starts giving the unknown error

```
[ERROR] : Elasticsearch - header missing (400)
[ERROR] : ElasticSearch - header missing
```

**How to reproduce it**

enable ElasticSearch in Falcosidekick with values:
   ```
elasticsearch:
      hostport: "https://elasticsearch-url:443"
      index: "Falco-dev"
      type: "event"
      minimumpriority: ""
      suffix: "daily"
      mutualtls: false
      checkcert: false
      username: "username"
      password: "pasword"
```

**Expected behaviour**

Elasticsearch should be able to create and add data successfully in the index.
Error should be clear where is the problem.

**Environment**

- Falco version:
falco image: 0.32.0
- System info:
- Cloud provider or hardware configuration: GKE
- OS:
- Kernel:
- Installation method: kubernetes
