### ISSUE TITLE
Falco starts but nothing happens

### ISSUE THREAD

**Issue by Diliz** [falcosecurity/charts#400]
**Describe the bug**

I managed to run falco on openshift (not so easy if you try to push it with a least privileged argo instance xD), the problem is it seems stuck at launch, maybe I failed something somewhere, but I got no real state of what's going wrong there :/

**How to reproduce it**

Installed latest falco on openshift with the latest falco helm chart, here the falco values:
```yaml

falco:

  image:
    pullPolicy: *pullPolicy
    pullSecrets: []
    registry: *registry
    repository: falcosecurity/falco
    tag: 0.32.2-slim # tried non slim version as well

  driver:
    enabled: true
    kind: "module"
    loader:
      enabled: true
      initContainer:
        enabled: true
        image:
          pullPolicy: *pullPolicy
          registry: *registry
          repository: falcosecurity/falco-driver-loader
          tag: 0.32.2
        args:
          - "--compile"

  auditLog:
    enabled: true

  falco:
    load_plugins: [json, k8saudit]
    watch_config_files: true
    rules_file:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml
      - /etc/falco/k8s_audit_rules.yaml
    json_output: true
    log_level: debug
    priority: debug

    stdout_output:
      enabled: true

  http_output: # enable for sidekick
    enabled: true

  scc: # true here enabled creation of Security Context Constraints in Openshift
    create: false #manually created for testing purpose (can't give the rights to argo for this)

  serviceAccount:
    create: true
```

And here the falco output:
```
Fri Aug 19 14:48:01 2022: Falco version 0.32.2
Fri Aug 19 14:48:01 2022: Falco initialized with configuration file /etc/falco/falco.yaml
Fri Aug 19 14:48:01 2022: Loading plugin (k8saudit) from file /usr/share/falco/plugins/libk8saudit.so
Fri Aug 19 14:48:01 2022: Loading plugin (json) from file /usr/share/falco/plugins/libjson.so
Fri Aug 19 14:48:01 2022: Configured rules filenames:
Fri Aug 19 14:48:01 2022: /etc/falco/falco_rules.yaml
Fri Aug 19 14:48:01 2022: /etc/falco/falco_rules.local.yaml
Fri Aug 19 14:48:01 2022: /etc/falco/k8s_audit_rules.yaml
Fri Aug 19 14:48:01 2022: Loading rules from file /etc/falco/falco_rules.yaml:
Fri Aug 19 14:48:02 2022: Loading rules from file /etc/falco/falco_rules.local.yaml:
Fri Aug 19 14:48:02 2022: Loading rules from file /etc/falco/k8s_audit_rules.yaml:
Fri Aug 19 14:48:02 2022: Watching /etc/falco/falco.yaml
Fri Aug 19 14:48:02 2022: Watching /etc/falco/falco_rules.yaml.
Fri Aug 19 14:48:02 2022: Watching /etc/falco/falco_rules.local.yaml.
Fri Aug 19 14:48:02 2022: Watching /etc/falco/k8s_audit_rules.yaml.
Fri Aug 19 14:48:02 2022: Starting internal webserver, listening on port 8765
```

Then nothing more :/

**Expected behaviour**

Events logged by falco

**Environment**

- Falco version:
0.32.2
- System info:
rhcos 4.18.x
- Cloud provider or hardware configuration:
- OS:
rhcos
- Kernel:
4.18.x
- Installation method:
helm chart + argo

**Additional context**

Openshift cluster:
- The security context constraints was manually added for testing purpose
- Machine config with kernel-devel added for kernel module building purpose
