### ISSUE TITLE
Add `extra.envFrom` option to falco chart 

### ISSUE THREAD

**Issue by rubensf** [falcosecurity/charts#414]
**Motivation**

While we already have [`extra.env`](https://github.com/falcosecurity/charts/blob/falco-2.2.0/falco/templates/pod-template.tpl#L99-L102), it's impossible to use references in those environments (eg `metadata.namespace`).

**Alternatives**

So far, I've had to do a `patchStrategicMerge`:

```
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco
  namespace: falco
spec:
  template:
    spec:
      containers:
        - name: falco
          env:
            - name: myEnv
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
```
**Additional context**
