### ISSUE TITLE
Template NOTES.txt contains incorrect information if deployment scenario is sued

### ISSUE THREAD

**Issue by trallnag** [falcosecurity/charts#448]
I have installed the chart with the following config:

```yaml
controller:
  kind: deployment

driver:
  enabled: false

collectors:
  enabled: false
```

Installation done with this command:

```
helm install falco falcosecurity/falco --values overrides.yaml
```

Command output contains this section:

```
NOTES:
Falco agents are spinning up on each node in your cluster. After a few
seconds, they are going to start monitoring your containers looking for
security issues.
```

It is talking about DaemonSet. But I am deploying Falco using the Deployment scenario.
