### ISSUE TITLE
Two empty environment variables are not allowed leading to errors in Falcosidekick

### ISSUE THREAD

**Issue by trallnag** [falcosecurity/charts#450]
This is about the falcosidekick chart.

By default, the following two values are set to empty string:

```
.Values.config.alertmanager.extralabels
.Values.config.alertmanager.extraannotations
```

This leads to the environment variables set to empty string as well:

```
ALERTMANAGER_EXTRALABELS: "{{ .Values.config.alertmanager.extralabels | b64enc }}"
ALERTMANAGER_EXTRAANNOTATIONS: "{{ .Values.config.alertmanager.extraannotations | b64enc }}"
```

But Falcosidekick does not allow these variables to be set to empty string. We get errors:

```
2023/01/20 13:20:20 [ERROR] : AlertManager - Extra field '' is not a valid prometheus labelData
2023/01/20 13:20:20 [ERROR] : AlertManager - Extra field '' is not a valid prometheus annotation
2023/01/20 13:20:20 [INFO]  : Falco Sidekick version: 2.27.0
```

Solution:

Only add variable to secret data if not empty.

**How to reproduce it**

Here is a minimal `overrides.yaml` for Falcosidekick chart:

```yaml
config:
  alertmanager:
    hostport: http://alertmanager-operated.observability.svc.cluster.local:9093
    endpoint: /alertmanager/api/v2/alerts
    minimumpriority: informational
    expireafter: "0"
```
