### ISSUE TITLE
falcosidekick: Cannot unmarshall number into string due to missing quotes

### ISSUE THREAD

**Issue by trallnag** [falcosecurity/charts#454]
This is regarding falcosidekick chart.

The value `.Values.webui.ttl` allows us to set TTL for Redis. It defaults to number 0:

```
webui:
  ttl: 0
```

It is injected as argument but only if not empty / not zero:

```
{{- if .Values.webui.ttl }}
- "-t"
- {{ .Values.webui.ttl }}
{{- end}}
```

This leads to error if number is anything but `0`:

> Error: failed to replace object: Deployment in version "v1" cannot be handled as a Deployment: json: cannot unmarshal number into Go struct field Container.spec.template.spec.containers.args of type string

Only strings are allowed as container arguments.

---

Example overrides:

```
webui:
  enabled: true
  replicaCount: 1
  loglevel: info
  user: "admin:admin"
  ttl: 2592000
```

Check the rendered YAML:

```
args:
- "-r"
- falcosidekick-ui-redis:6379
- "-t"
- 2.592e+06
- "-l"
- info
- "-u"
- admin:admin
```
