### ISSUE TITLE
Falcosidekick-ui Redis Error: interface conversion: interface {} is nil, not string

### ISSUE THREAD

**Issue by j771** [falcosecurity/charts#463]
Falco UI runs well on initial deployment but after running for a day the ui pods get the following error when trying to load the UI. The pods do not recover unless the redis storage is wiped out.
The redis is currently over provisioned and not running out of disk space or memory.

Error log from falcosidekick-ui pod:
```
echo: http: panic serving <IP>:<PORT>: interface conversion: interface {} is nil, not string
goroutine 399025 [running]:
net/http.(*conn).serve.func1()
	go/src/net/http/server.go:1825 +0xbf
panic({0x94e1c0, 0xc001e65da0})
	go/src/runtime/panic.go:844 +0x258
github.com/falcosecurity/falcosidekick-ui/internal/database/redis.CountKeyBy(0x7fdff87806f8?, 0xc0002b7540)
	/home/circleci/project/internal/database/redis/count.go:43 +0x7c5
github.com/falcosecurity/falcosidekick-ui/internal/events.CountBy(0x9d75e0?)
	/home/circleci/project/internal/events/count.go:24 +0x4a
github.com/falcosecurity/falcosidekick-ui/internal/api.CountByEvent({0xac1300, 0xc0002d2e60})
	/home/circleci/project/internal/api/api.go:98 +0x1f6
github.com/labstack/echo/v4/middleware.BasicAuthWithConfig.func1.1({0xac1300, 0xc0002d2e60})
	pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/basic_auth.go:93 +0x4a5
github.com/labstack/echo/v4.(*Echo).add.func1({0xac1300, 0xc0002d2e60})
	pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x51
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0002aad80, {0xabdd48?, 0xc0018cb880}, 0xc0019c7500)
	pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x3bc
net/http.serverHandler.ServeHTTP({0xc001f5b4d0?}, {0xabdd48, 0xc0018cb880}, 0xc0019c7500)
	go/src/net/http/server.go:2916 +0x43b
net/http.(*conn).serve(0xc001f86000, {0xabe120, 0xc00014f530})
	go/src/net/http/server.go:1966 +0x5d7
created by net/http.(*Server).Serve
	go/src/net/http/server.go:3071 +0x4db
```

Kubernetes v1.22
Deployed with Helm chart falcosecurity/falco --version 2.5.4
Helm values file:
```
falcosidekick:
  enabled: true
  webui:
    enabled: true
    ttl: 604800
    redis:
      storageSize: 30Gi
      resources:
        limits:
          cpu: 800m
          memory: 12Gi
        requests:
          cpu: 300m
          memory: 10Gi
```
