### ISSUE TITLE
Replace /dev mount with /dev/falco mount

### ISSUE THREAD

**Issue by Jeroen0494** [falcosecurity/charts#471]
**Motivation**

In the current situation, the entire host `/dev` directory is mounted in the Falco container. This exposes a lot of seemingly unnecessary characted and block devices to the container. Instead of mounting the entire directory, only mount the `/dev/falco*` characted devices.

**Feature**
Abbreviated examples.

Replace this:
```
spec:
  template:
    spec:
      containers:
      - args:
        - /usr/bin/falco
        - --cri
        - /run/containerd/containerd.sock
        - -K
        - /var/run/secrets/kubernetes.io/serviceaccount/token
        - -k
        - https://$(KUBERNETES_SERVICE_HOST)
        - --k8s-node
        - $(FALCO_K8S_NODE_NAME)
        - -pk
        env:
        - name: FALCO_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.io/falcosecurity/falco-no-driver:0.34.1
        volumeMounts:
        - mountPath: /host/dev/
          name: dev-fs
          readOnly: true
      volumes
      - hostPath:
          path: /dev
          type: "
        name: dev-fs
```

With this:
```
spec:
  template:
    spec:
      containers:
      - args:
        - /usr/bin/falco
        - --cri
        - /run/containerd/containerd.sock
        - -K
        - /var/run/secrets/kubernetes.io/serviceaccount/token
        - -k
        - https://$(KUBERNETES_SERVICE_HOST)
        - --k8s-node
        - $(FALCO_K8S_NODE_NAME)
        - -pk
        env:
        - name: FALCO_K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: docker.io/falcosecurity/falco-no-driver:0.34.1
        volumeMounts:
        - mountPath: /host/dev/falco0
          name: dev-falco0
          readOnly: true
        - mountPath: /host/dev/falco1
          name: dev-falco1
          readOnly: true
        - mountPath: /host/dev/falco2
          name: dev-falco2
          readOnly: true
        - mountPath: /host/dev/falco3
          name: dev-falco3
          readOnly: true
      volumes
      - hostPath:
          path: /dev/falco0
          type: CharDevice
        name: dev-falco0
      - hostPath:
          path: /dev/falco1
          type: CharDevice
        name: dev-falco1
      - hostPath:
          path: /dev/falco2
          type: CharDevice
        name: dev-falco2
      - hostPath:
          path: /dev/falco3
          type: CharDevice
        name: dev-falco3
```

I'm guessing the number of falco character devices are dynamically generated by something, maybe we can create a foreach loop with Helm to create as many as are necessary.

I already tried it out, and it seems to work:
```
Name:         falco-57c8f
Namespace:    falco
Priority:     0
Node:         mediaserver.fritz.box/192.168.178.43
Start Time:   Tue, 28 Feb 2023 17:50:51 +0100
Labels:       app.kubernetes.io/instance=falco
              app.kubernetes.io/name=falco
              controller-revision-hash=69f4d79b74
              pod-template-generation=10
Annotations:  checksum/config: 22abe02be56314f4d85a5c4a0c3c06bb8856ef4ccc5be26f27da47b6590b5b82
              checksum/rules: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
              cni.projectcalico.org/containerID: 5db6b99eb6d77d7a4b7ca38c8a83bcc9b3fa1d5e8c91f53815fa441bc21f69e9
              cni.projectcalico.org/podIP: 10.233.105.152/32
              cni.projectcalico.org/podIPs: 10.233.105.152/32
Status:       Running
IP:           10.233.105.152
IPs:
  IP:           10.233.105.152
Controlled By:  DaemonSet/falco
Init Containers:
  falco-driver-loader:
    Container ID:   containerd://8d4b1a17f606935a9033bfa083e228dcbf1ad94f44f0d426131609327693bd0e
    Image:          docker.io/falcosecurity/falco-driver-loader:0.34.1
    Image ID:       docker.io/falcosecurity/falco-driver-loader@sha256:1bcd4984b3748af1a48c585fb3ee94953a4f2a7ece0750895ad6c28355532d45
    Port:           <none>
    Host Port:      <none>
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 28 Feb 2023 17:50:53 +0100
      Finished:     Tue, 28 Feb 2023 17:50:54 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /host/boot from boot-fs (ro)
      /host/etc from etc-fs (ro)
      /host/lib/modules from lib-modules (rw)
      /host/proc from proc-fs (ro)
      /host/usr from usr-fs (ro)
      /root/.falco from root-falco-fs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pf45p (ro)
  falcoctl-artifact-install:
    Container ID:  containerd://6d0a491ecaa887e3c760d3eea46069c6052783676b54e7b4d2736821adf4bccc
    Image:         docker.io/falcosecurity/falcoctl:0.4.0
    Image ID:      docker.io/falcosecurity/falcoctl@sha256:0764be042b2fece8d60e5d24448dc1d596a11e14d4d0190bc8d8fe528e42cfb9
    Port:          <none>
    Host Port:     <none>
    Args:
      artifact
      install
      --verbose
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 28 Feb 2023 17:50:56 +0100
      Finished:     Tue, 28 Feb 2023 17:50:58 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/falcoctl from falcoctl-config-volume (rw)
      /plugins from plugins-install-dir (rw)
      /rulesfiles from rulesfiles-install-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pf45p (ro)
Containers:
  falco:
    Container ID:  containerd://ce2e1f421d8cb1447af6158a464d69928cbf4f39dac1323a9d6797261e7d9e93
    Image:         docker.io/falcosecurity/falco-no-driver:0.34.1
    Image ID:      docker.io/falcosecurity/falco-no-driver@sha256:3dba78bb34de85b54e71d979a97b8cac5577ae87923bb4c19b08c337e138ec7d
    Port:          <none>
    Host Port:     <none>
    Args:
      /usr/bin/falco
      --cri
      /run/containerd/containerd.sock
      -K
      /var/run/secrets/kubernetes.io/serviceaccount/token
      -k
      https://$(KUBERNETES_SERVICE_HOST)
      --k8s-node
      $(FALCO_K8S_NODE_NAME)
      -pk
    State:          Running
      Started:      Tue, 28 Feb 2023 17:51:00 +0100
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  1Gi
    Requests:
      cpu:      100m
      memory:   512Mi
    Liveness:   http-get http://:8765/healthz delay=60s timeout=5s period=15s #success=1 #failure=3
    Readiness:  http-get http://:8765/healthz delay=30s timeout=5s period=15s #success=1 #failure=3
    Environment:
      FALCO_K8S_NODE_NAME:   (v1:spec.nodeName)
    Mounts:
      /etc/falco from rulesfiles-install-dir (rw)
      /etc/falco/certs from certs-volume (ro)
      /etc/falco/falco.yaml from falco-yaml (rw,path="falco.yaml")
      /host/dev/falco0 from dev-falco0 (ro)
      /host/dev/falco1 from dev-falco1 (ro)
      /host/dev/falco2 from dev-falco2 (ro)
      /host/dev/falco3 from dev-falco3 (ro)
      /host/proc from proc-fs (rw)
      /host/run/containerd/containerd.sock from containerd-socket (rw)
      /root/.falco from root-falco-fs (rw)
      /sys/module/falco from sys-fs (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pf45p (ro)
  falcoctl-artifact-follow:
    Container ID:  containerd://270b2a7a35146d675012cc0093a8f63d0180f323724718ac0d9c556b80eb6146
    Image:         docker.io/falcosecurity/falcoctl:0.4.0
    Image ID:      docker.io/falcosecurity/falcoctl@sha256:0764be042b2fece8d60e5d24448dc1d596a11e14d4d0190bc8d8fe528e42cfb9
    Port:          <none>
    Host Port:     <none>
    Args:
      artifact
      follow
      --verbose
    State:          Running
      Started:      Tue, 28 Feb 2023 17:51:01 +0100
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/falcoctl from falcoctl-config-volume (rw)
      /plugins from plugins-install-dir (rw)
      /rulesfiles from rulesfiles-install-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-pf45p (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  plugins-install-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  rulesfiles-install-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  root-falco-fs:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  boot-fs:
    Type:          HostPath (bare host directory volume)
    Path:          /boot
    HostPathType:  
  lib-modules:
    Type:          HostPath (bare host directory volume)
    Path:          /lib/modules
    HostPathType:  
  usr-fs:
    Type:          HostPath (bare host directory volume)
    Path:          /usr
    HostPathType:  
  etc-fs:
    Type:          HostPath (bare host directory volume)
    Path:          /etc
    HostPathType:  
  dev-falco0:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/falco0
    HostPathType:  CharDevice
  dev-falco1:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/falco1
    HostPathType:  CharDevice
  dev-falco2:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/falco2
    HostPathType:  CharDevice
  dev-falco3:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/falco3
    HostPathType:  CharDevice
  sys-fs:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/module/falco
    HostPathType:  
  containerd-socket:
    Type:          HostPath (bare host directory volume)
    Path:          /run/containerd/containerd.sock
    HostPathType:  
  proc-fs:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:  
  falcoctl-config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      falco-falcoctl
    Optional:  false
  falco-yaml:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      falco
    Optional:  false
  certs-volume:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  falco-server-certs
    Optional:    false
  kube-api-access-pf45p:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 Exists:NoSchedule
                             node-role.kubernetes.io/control-plane:NoSchedule
                             node-role.kubernetes.io/master:NoSchedule
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  17m   default-scheduler  Successfully assigned falco/falco-57c8f to mediaserver.fritz.box
  Normal  Pulling    17m   kubelet            Pulling image "docker.io/falcosecurity/falco-driver-loader:0.34.1"
  Normal  Pulled     17m   kubelet            Successfully pulled image "docker.io/falcosecurity/falco-driver-loader:0.34.1" in 920.483209ms (920.489095ms including waiting)
  Normal  Created    17m   kubelet            Created container falco-driver-loader
  Normal  Started    17m   kubelet            Started container falco-driver-loader
  Normal  Pulling    17m   kubelet            Pulling image "docker.io/falcosecurity/falcoctl:0.4.0"
  Normal  Pulled     17m   kubelet            Successfully pulled image "docker.io/falcosecurity/falcoctl:0.4.0" in 860.033073ms (860.037968ms including waiting)
  Normal  Created    17m   kubelet            Created container falcoctl-artifact-install
  Normal  Started    17m   kubelet            Started container falcoctl-artifact-install
  Normal  Pulling    17m   kubelet            Pulling image "docker.io/falcosecurity/falco-no-driver:0.34.1"
  Normal  Pulled     17m   kubelet            Successfully pulled image "docker.io/falcosecurity/falco-no-driver:0.34.1" in 822.252433ms (822.25732ms including waiting)
  Normal  Created    17m   kubelet            Created container falco
  Normal  Started    17m   kubelet            Started container falco
  Normal  Pulling    17m   kubelet            Pulling image "docker.io/falcosecurity/falcoctl:0.4.0"
  Normal  Pulled     16m   kubelet            Successfully pulled image "docker.io/falcosecurity/falcoctl:0.4.0" in 830.043625ms (830.048666ms including waiting)
  Normal  Created    16m   kubelet            Created container falcoctl-artifact-follow
  Normal  Started    16m   kubelet            Started container falcoctl-artifact-follow
```
