### ISSUE TITLE
Allow program_output to built-in falcosidekick chart

### ISSUE THREAD

**Issue by rubensf** [falcosecurity/charts#476]
**Motivation**

It is currently impossible to use the built in falcosidekick chart with a program output, eg

```
falco:
  http_output:
    enabled: false
  program_output:
    enabled: true
    program: jq ".output_fields.\"custom_field\" = \"${CUSTOM_ENV_VAR}\"" |
      curl -sSL -d @- -X POST -A falcosecurity/falco http://falco-falcosidekick:2801
```

Because of [the lines here](https://github.com/falcosecurity/charts/blob/4c13856/falco/templates/_helpers.tpl#L154-L161), that `http_output` will be force enabled, which in my experience creates duplicate information.

**Feature**

I'd like for there to be additional checks instead of force setting http_output to true, for example:

```
{{- if .Values.falcosidekick.enabled  -}}
```

We can instead check if 

```
{{- if and .Values.falcosidekick.enabled (not .Values.falco.program_output.enabled)  -}}
```

Alternatively, we can have another setting such as `falco.add_sidekick_defaults` which is default to true.

**Alternatives**

Currently, I have to install the falcosidekick chart separately from the falco one, (ie using `https://github.com/falcosecurity/charts/releases/download/falcosidekick-<version>/falcosidekick-<version>.tgz`). That is a feasible workaround but it makes our system unnecessarily complicated.

**Comment by Issif** [comment]
Hi,

I would like to know what is your finale use case. I  see you want to add a custom fields in the output fields based on an env var. Falcosidekick can do so by design.

**Comment by Issif** [comment]
If I take your example, something like that should work:
```yaml
falcosidekick:
  enabled: true
  config:
    extraEnv:
      - name: MY_SECRET
        valueFrom:
          fieldRef:
            fieldPath: metadata.annotations['super_secret']
      - name: CUSTOMFIELDS
        value: "k8s.cluster.name:%MY_SECRET"
```
Since v2.27.0, we can use env vars for custom fields. If the value starts with a %, Falcosidekick replaces it automatically with what is in its env.

```
customfields: # custom fields are added to falco events, if the value starts with % the relative env var is used
```

Does it make sense?
