### ISSUE TITLE
Pass environment variables to falcoctl install and follow

### ISSUE THREAD

**Issue by msardara** [falcosecurity/charts#486]
**Describe the bug**

Hello, I am trying to pass some environment variables to the falcoctl `init` and `follow` containers.

I noticed the expected parameters for the env key is a [map](https://github.com/falcosecurity/charts/blob/master/falco/values.yaml#L349), but I am not 100% sure how to pass my env variables to this map. In fact I was expecting a list.

If I try to pass the variables in this way:

```yaml
falcoctl:
  artifact:
    install:
      enabled: true
      env:
        envVariable1:
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        envVariable2: value
```

The installation of course fails with this error, as the env: field in the pod manifest is expecting a list of env:

```
Error: INSTALLATION FAILED: DaemonSet in version "v1" cannot be handled as a DaemonSet: json: cannot unmarshal object into Go struct field Container.spec.template.spec.containers.env of type []v1.EnvVar
```

If I try to force-pass an array

```yaml
falcoctl:
  artifact:
    install:
      enabled: true
      env:
        - name: envVariable1
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        - name: envVariable2
          value: value
```

the installation seems to succeed but I get these warning messages:

```
coalesce.go:220: warning: cannot overwrite table with non table for dragonfly-data-collector.falco.falcoctl.artifact.install.env (map[])
coalesce.go:220: warning: cannot overwrite table with non table for dragonfly-data-collector.falco.falcoctl.artifact.install.env (map[])
```

**How to reproduce it**

With this values.yaml:

```
falcoctl:
  artifact:
    install:
      enabled: true
      env:
        envVariable1:
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        envVariable2: value
```

The installation fails:

```
helm install falco-test falcosecurity/falco -f ./values.yaml
Error: INSTALLATION FAILED: DaemonSet in version "v1" cannot be handled as a DaemonSet: json: cannot unmarshal object into Go struct field Container.spec.template.spec.initContainers.env of type []v1.EnvVar
```

With this values.yaml

```
falcoctl:
  artifact:
    install:
      enabled: true
      env:
        - name: envVariable1
          valueFrom:
            secretKeyRef:
              name: secret
              key: password
        - name: envVariable2
          value: value
```

Installation succeeds but I get few warning messages

```
helm install falco-test falcosecurity/falco -f ./values.yaml
coalesce.go:220: warning: cannot overwrite table with non table for falco.falcoctl.artifact.install.env (map[])
coalesce.go:220: warning: cannot overwrite table with non table for falco.falcoctl.artifact.install.env (map[])
NAME: falco-test
LAST DEPLOYED: Fri May  5 10:35:54 2023
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
Falco agents are spinning up on each node in your cluster. After a few
seconds, they are going to start monitoring your containers looking for
security issues.


No further action should be required.


Tip:
You can easily forward Falco events to Slack, Kafka, AWS Lambda and more with falcosidekick.
Full list of outputs: https://github.com/falcosecurity/charts/tree/master/falcosidekick.
You can enable its deployment with `--set falcosidekick.enabled=true` or in your values.yaml.
See: https://github.com/falcosecurity/charts/blob/master/falcosidekick/values.yaml for configuration values.
```

**Expected behaviour**

I am not sure if this is the expected behavior or I am passing the environment variables in the wrong way.

**Screenshots**

**Environment**

- Chart version: 3.1.4
- Falco version: 0.34.1
- System info: k8s cluster

**Additional context**
