### ISSUE TITLE
exporter Chart v0.9.5 breaks daemonset when PSP is activated

### ISSUE THREAD

**Issue by hardwarefresser** [falcosecurity/charts#494]
**Describe the bug**
[PR #487](https://github.com/falcosecurity/charts/pull/487/files) introduces a security context in values.yaml for falco-exporter which includes a seccomp profile:
```yaml
securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  privileged: false
  seccompProfile:
    type: RuntimeDefault
```

When the chart is deployed on an environment with PSP enabled, the [PSP delivered with the Chart](https://github.com/falcosecurity/charts/blob/master/falco-exporter/templates/podsecuritypolicy.yaml) seems not to allow the Seccomp Profile to be set and therefore prevents the pod admission:

```
$ k get events  | grep exporter
Warning   FailedCreate daemonset/falco-falco-exporter  Error creating: pods "falco-falco-exporter-" is forbidden: 
PodSecurityPolicy: unable to admit pod: [pod.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/falco-exporter]:
Forbidden: seccomp may not be set
```
According to [this comment](https://github.com/rancher/rke2/issues/2156#issuecomment-1031436119), adding `seccomp.security.alpha.kubernetes.io/allowedProfileNames: '*'` to the PSP annotations should solve the problem. I did a quick test and admission was not prevented anymore.
However, as we want to use the seccomp profile `RuntimeDefault`, it would be better to add `seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'RuntimeDefault'` as PSP annotation. I will also try this and get back. But I would appreciate of someone could double check the whole issue.

**Expected behaviour**
PSP should not prevent the pods with seccomp

**Environment**

- Falco version: Falco version: 0.34.1 (x86_64)

- Installation method: Kubernetes using Helm, PSP activated

**Additional context**
Issue https://github.com/falcosecurity/charts/issues/481

**Comment by hardwarefresser** [comment]
Setting `seccompProfile: null` in the values.yaml to override the default value also works.

**Comment by hardwarefresser** [comment]
The best solution should be configuring the PSP as follows via [values.yaml](https://github.com/falcosecurity/charts/blob/master/falco-exporter/values.yaml):
```yaml
podSecurityPolicy:
  # Specifies whether a PSP, Role and RoleBinding should be created
  create: true
  # Annotations to add to the PSP, Role and RoleBinding
  annotations:
    seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
```
With this annotations, the PSP will allow the seccomp profile set in the default security context introduced in PR #487 
I will open a PR to add the above mentioned annotations by default in values.yaml. This way, the admission of the pods will not be prevented anymore in environments with enabled PSP.
