### ISSUE TITLE
Falco Sidekick redis taking huge amount of memory

### ISSUE THREAD

**Issue by dcardellino** [falcosecurity/charts#499]
**Describe the bug**

The pod `falco-falcosidekick-ui-redis-0` takes huge amounts of memory. In our setup currently 19Gi and is causing the node to get `NotReady`.

**How to reproduce it**

Install falco with the helm chart and the following values:

```yaml
driver:
  enabled: true
  kind: modern-bpf
collectors:
  enabled: true
controller:
  kind: daemonset
falcosidekick:
  enabled: true
  config:
    slack:
      minimumpriority: 'error'
  redis:
    storageSize: "20Gi"
  webui:
    enabled: true
```
**Expected behaviour**

Falco UI Redis runs at normal memory level.

**Screenshots**

![Screenshot 2023-06-07 at 12 24 34](https://github.com/falcosecurity/charts/assets/33149391/10d0a027-7229-4736-b74f-78b79d59647b)

**Environment**

- Falco version: `Falco version: 0.34.1 (x86_64)`

- System info: 

```json
{
  "machine": "x86_64",
  "nodename": "falco-2dmwf",
  "release": "5.15.0-73-generic",
  "sysname": "Linux",
  "version": "#80-Ubuntu SMP Mon May 15 15:18:26 UTC 2023"
}
```
- Cloud provider or hardware configuration: Hetzner Cloud
- OS: Ubuntu 22.04

- Kernel:

- Installation method: Kubernetes

**Additional context**
