### ISSUE TITLE
k8saudit plugin does not work

### ISSUE THREAD

**Issue by avramenkovladyslav** [falcosecurity/charts#510]
**Description:** 
After installation of k8saudit, rules doesn't work

**Code snippet**

```
driver:
  enabled: false
collectors:
  enabled: false

falco:
  grpc:
    enabled: true
  grpc_output:
    enabled: true
  plugins:
    - name: k8saudit
      library_path: libk8saudit.so
      init_config:
        sslCertificate: /etc/falco/falco.pem
      open_params: "http://:9765/k8s-audit"
    - name: json
      library_path: libjson.so
      init_config: ""
  load_plugins: [k8saudit, json]

customRules:
  rules-network.yaml: |-
    - required_engine_version: 15

    - required_plugin_versions:
      - name: k8saudit
        version: 0.6.0
        alternatives:
          - name: k8saudit-eks
            version: 0.2.0
      - name: json
        version: 0.7.0

    - macro: not_test_endpoint
      condition: (not ka.uri=test)

    - rule: All K8s Audit Events
      desc: All K8s Audit network Events
      condition: not_test_endpoint
      output: K8s Audit Event received (user=%ka.user.name verb=%ka.verb uri=%ka.uri obj=%jevt.obj)
      priority: DEBUG
      source: k8s_audit
      tags: [k8s]
```

Than you can make Deployment with ubuntu image for example and try to `curl google.com`. Rule doesn't trigger
I have falcosidekick on top of this configuration so i get all alerts to Slack immediately.
When im setting `driver.enable=false` and `collectors.enable=false` all my alerts stop working (previously i received "Terminal shell in container" when i executed pod), and chart values says "Always set it to false when using Falco with plugins".

Additionally i tried [this falco documentation](https://falco.org/blog/k8saudit-eks-plugin/) to download latest plugin versions and in this case i received error 
`Runtime error: cannot load plugin /usr/share/falco/plugins/libk8saudit.so: plugin required API version '2.0.0' not compatible with the framework's API version '3.0.0': major versions disagree. Exiting.` 

**Expected behaviour**
Both native and plugin rules working correctly together

**Environment**
- AWS EKS 1.23
- Falco versions: 0.35.1, 0.32.2, 0.32.0
