### ISSUE TITLE
Allow installing falco-exporter as a dependency of falco

### ISSUE THREAD

**Issue by sambonbonne** [falcosecurity/charts#523]
**Motivation**

Right now, the *falco* chart allow setting `falcosidekick.enabled` in order to install Falco Sidekick alongside Falco.

But it does not provide the same possibility for Falco Exporter.

**Feature**

It would be nice, for consistency, to add the ability to install and configure Falco Exporter with Falco, like for Falco Sidekick.

Sidekick is a dependency of the Falco chart (with `falcosidekick.enabled: false` by default, which is nice because it's opt-in):

```yaml
dependencies:
- condition: falcosidekick.enabled
  name: falcosidekick
  repository: https://falcosecurity.github.io/charts
  version: …
```

So maybe it's possible to add the Exporter the same way, with a `falco-expoter.enabled: false` default value:

```yaml
dependencies:
- condition: falco-expoter.enabled
  name: falco-exporter
  repository: https://falcosecurity.github.io/charts
  version: …
```

**Alternatives**

The current alternative is to install Falco Expoter with its own chart.

**Additional context**

I don't know why Sidekick can be installed and configured alongside Falco but the Expoter can't, if there is an explanation I would be happy to read it.

I don't know if this is relevant, but if it's possible for the Expoter to be added, maybe the Event Generator can be added too? If yes, does it deserve a specific issue?
