### ISSUE TITLE
falco Run time error in k8's

### ISSUE THREAD

**Issue by datan-ew** [falcosecurity/charts#573]
Describe the bug:

     falco when running on few clusters as a Daemon set throws the below error on replicaset_handler_state and k8s_deployment_handler_state eventually the falco container pods keep on restarting

Mon Oct 30 07:20:55 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Mon Oct 30 07:20:55 2023: Starting health webserver with threadiness 2, listening on port 8765
Mon Oct 30 07:20:55 2023: Loaded event sources: syscall
Mon Oct 30 07:20:55 2023: Enabled event sources: syscall
Mon Oct 30 07:20:55 2023: Opening 'syscall' source with Kernel module
k8s_handler (k8s_deployment_handler_state::collect_data()[https://172.20.0.1/] an error occurred while receiving data from k8s_deployment_handler_state, m_blocking_socket=1, m_watching=0, SSL Socket handler (k8s_deployment_handler_state): Connection closed.

Mon Oct 30 23:38:43 2023: Falco version: 0.36.1 (x86_64)
Mon Oct 30 23:38:43 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Mon Oct 30 23:38:43 2023: Loading rules from file /etc/falco/falco_rules.yaml
Mon Oct 30 23:38:43 2023: Disabling rules matching substring: Clear Log Activities
Mon Oct 30 23:38:43 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Mon Oct 30 23:38:43 2023: Starting health webserver with threadiness 2, listening on port 8765
Mon Oct 30 23:38:43 2023: Loaded event sources: syscall
Mon Oct 30 23:38:43 2023: Enabled event sources: syscall
Mon Oct 30 23:38:43 2023: Opening 'syscall' source with Kernel module

{"hostname":"falco-helm-7v77w","output":"Falco internal: syscall event drop. 6 system calls dropped in last second.","output_fields":{"ebpf_enabled":"0","n_drops":"6","n_drops_buffer_clone_fork_enter":"0","n_drops_buffer_clone_fork_exit":"0","n_drops_buffer_close_exit":"0","n_drops_buffer_connect_enter":"0","n_drops_buffer_connect_exit":"0","n_drops_buffer_dir_file_enter":"0","n_drops_buffer_dir_file_exit":"0","n_drops_buffer_execve_enter":"0","n_drops_buffer_execve_exit":"0","n_drops_buffer_open_enter":"0","n_drops_buffer_open_exit":"0","n_drops_buffer_other_interest_enter":"0","n_drops_buffer_other_interest_exit":"0","n_drops_buffer_proc_exit":"0","n_drops_buffer_total":"6","n_drops_bug":"0","n_drops_page_faults":"0","n_drops_scratch_map":"0","n_evts":"10"},"priority":"Debug","rule":"Falco internal: syscall event drop","source":"internal","time":"2023-10-31T01:27:27.679575737Z"}
{"hostname":"falco-helm-7v77w","output":"Falco internal: syscall event drop. 48862 system calls dropped in last second.","output_fields":{"ebpf_enabled":"0","n_drops":"48862","n_drops_buffer_clone_fork_enter":"0","n_drops_buffer_clone_fork_exit":"4","n_drops_buffer_close_exit":"3","n_drops_buffer_connect_enter":"0","n_drops_buffer_connect_exit":"0","n_drops_buffer_dir_file_enter":"0","n_drops_buffer_dir_file_exit":"0","n_drops_buffer_execve_enter":"0","n_drops_buffer_execve_exit":"0","n_drops_buffer_open_enter":"0","n_drops_buffer_open_exit":"0","n_drops_buffer_other_interest_enter":"0","n_drops_buffer_other_interest_exit":"0","n_drops_buffer_proc_exit":"0","n_drops_buffer_total":"48862","n_drops_bug":"0","n_drops_page_faults":"0","n_drops_scratch_map":"0","n_evts":"151886"},"priority":"Debug","rule":"Falco internal: syscall event drop","source":"internal","time":"2023-10-31T01:48:00.259073906Z"}
{"hostname":"falco-helm-7v77w","output":"Falco internal: syscall event drop. 289922 system calls dropped in last second.","output_fields":{"ebpf_enabled":"0","n_drops":"289922","n_drops_buffer_clone_fork_enter":"0","n_drops_buffer_clone_fork_exit":"0","n_drops_buffer_close_exit":"0","n_drops_buffer_connect_enter":"0","n_drops_buffer_connect_exit":"0","n_drops_buffer_dir_file_enter":"0","n_drops_buffer_dir_file_exit":"0","n_drops_buffer_execve_enter":"0","n_drops_buffer_execve_exit":"0","n_drops_buffer_open_enter":"0","n_drops_buffer_open_exit":"0","n_drops_buffer_other_interest_enter":"0","n_drops_buffer_other_interest_exit":"0","n_drops_buffer_proc_exit":"0","n_drops_buffer_total":"289922","n_drops_bug":"0","n_drops_page_faults":"0","n_drops_scratch_map":"0","n_evts":"397760"},"priority":"Debug","rule":"Falco internal: syscall event drop","source":"internal","time":"2023-10-31T01:56:56.886100585Z"}
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
Error: Socket handler (k8s_node_handler_event, socket=5) SSL errors:
error:0A000126:SSL routines::unexpected eof while reading

manojkumar@MBUSIRED-M-YTQ0 ~ % kubectl logs falco-helm-xczss -n falco -c falco --previous
Mon Oct 30 23:02:25 2023: Falco version: 0.36.1 (x86_64)
Mon Oct 30 23:02:25 2023: Falco initialized with configuration file: /etc/falco/falco.yaml
Mon Oct 30 23:02:25 2023: Loading rules from file /etc/falco/falco_rules.yaml
Mon Oct 30 23:02:25 2023: Disabling rules matching substring: Clear Log Activities
Mon Oct 30 23:02:25 2023: The chosen syscall buffer dimension is: 8388608 bytes (8 MBs)
Mon Oct 30 23:02:25 2023: Starting health webserver with threadiness 2, listening on port 8765
Mon Oct 30 23:02:25 2023: Loaded event sources: syscall
Mon Oct 30 23:02:25 2023: Enabled event sources: syscall
Mon Oct 30 23:02:25 2023: Opening 'syscall' source with Kernel module
k8s_handler (k8s_deployment_handler_state::collect_data()[https://172.20.0.1] an error occurred while receiving data from k8s_deployment_handler_state, m_blocking_socket=1, m_watching=0, SSL Socket handler (k8s_deployment_handler_state): Connection closed.
{"hostname":"falco-helm-xczss","output":"Falco internal: syscall event drop. 45850 system calls dropped in last second.","output_fields":{"ebpf_enabled":"0","n_drops":"45850","n_drops_buffer_clone_fork_enter":"0","n_drops_buffer_clone_fork_exit":"5","n_drops_buffer_close_exit":"0","n_drops_buffer_connect_enter":"0","n_drops_buffer_connect_exit":"0","n_drops_buffer_dir_file_enter":"0","n_drops_buffer_dir_file_exit":"0","n_drops_buffer_execve_enter":"0","n_drops_buffer_execve_exit":"0","n_drops_buffer_open_enter":"0","n_drops_buffer_open_exit":"1","n_drops_buffer_other_interest_enter":"0","n_drops_buffer_other_interest_exit":"0","n_drops_buffer_proc_exit":"0","n_drops_buffer_total":"45850","n_drops_bug":"0","n_drops_page_faults":"0","n_drops_scratch_map":"0","n_evts":"146668"},"priority":"Debug","rule":"Falco internal: syscall event drop","source":"internal","time":"2023-10-30T23:02:27.426752041Z"}
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
Error: Socket handler (k8s_namespace_handler_event, socket=5) SSL errors:
error:0A000126:SSL routines::unexpected eof while reading

k8s_handler (k8s_replicaset_handler_state::collect_data()[https://172.20.0.1/] an error occurred while receiving data from k8s_replicaset_handler_state, m_blocking_socket=1, m_watching=0, SSL Socket handler (k8s_replicaset_handler_state): Connection closed.
k8s_handler (k8s_deployment_handler_state::collect_data()[https://172.20.0.1/] an error occurred while receiving data from k8s_deployment_handler_state, m_blocking_socket=1, m_watching=0, SSL Socket handler (k8s_deployment_handler_state): Connection closed.
{"hostname":"falco-helm-mxdv9","output":"Falco internal: syscall event drop. 3840899 system calls dropped in last second.","output_fields":{"ebpf_enabled":"0","n_drops":"3840899","n_drops_buffer_clone_fork_enter":"0","n_drops_buffer_clone_fork_exit":"0","n_drops_buffer_close_exit":"12793","n_drops_buffer_connect_enter":"2","n_drops_buffer_connect_exit":"1","n_drops_buffer_dir_file_enter":"0","n_drops_buffer_dir_file_exit":"0","n_drops_buffer_execve_enter":"0","n_drops_buffer_execve_exit":"7","n_drops_buffer_open_enter":"58","n_drops_buffer_open_exit":"59","n_drops_buffer_other_interest_enter":"0","n_drops_buffer_other_interest_exit":"0","n_drops_buffer_proc_exit":"0","n_drops_buffer_total":"3840899","n_drops_bug":"0","n_drops_page_faults":"0","n_drops_scratch_map":"0","n_evts":"4679747"},"priority":"Debug","rule":"Falco internal: syscall event drop","source":"internal","time":"2023-10-30T15:50:17.395813123Z"}
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
Error: Socket handler (k8s_node_handler_event, socket=14) SSL errors:
error:0A000126:SSL routines::unexpected eof while reading
2023-10-30T15:57:43.575011595Z

**How to reproduce it**

    We are using the official helm chart of version: 3.8.1 and falco is running on version: "0.36.1".

**Expected behaviour**

   No runtime error

**Screenshots**

**Environment**

- Falco version:
     "0.36.1"
- System info:

  "machine": "x86_64",
  "nodename": "falco-helm-5zmh9",
  "release": "5.15.0-1041-aws",
  "sysname": "Linux",
  "version": "# 46~20.04.1-Ubuntu "

- Kernel: Debian GNU/Linux

Linux falco-helm-5zmh9 5.15.0-1041-aws # 46~20.04.1-Ubuntu SMP
- Installation method:
deployed on EKS Clusters using ArgoCD Application mentioning source as charts on the argocd application manifest.

**Comment by Andreagit97** [comment]
ei @datan-ew thank you for reporting! Are you deploying Falco with the Kubernetes collector enabled? If yes, I would suggest you to disable the Kubernetes collector putting it to false :point_down: The actual Kubernetes collector has some issues that we will solve in the next Falco release (0.37.0), at the moment probably the best solution is to disable it
```yaml
collectors:

  kubernetes:
    # -- Enable Kubernetes meta data collection via a connection to the Kubernetes API server.
    # When this option is disabled, Falco falls back to the container annotations to grap the meta data.
    # In such a case, only the ID, name, namespace, labels of the pod will be available.
    enabled: false
    # -- The apiAuth value is to provide the authentication method Falco should use to connect to the Kubernetes API.
    # The argument's documentation from Falco is provided here for reference:
    #
    #  <bt_file> | <cert_file>:<key_file[#password]>[:<ca_cert_file>], --k8s-api-cert <bt_file> | <cert_file>:<key_file[#password]>[:<ca_cert_file>]
    #     Use the provided files names to authenticate user and (optionally) verify the K8S API server identity.
    #     Each entry must specify full (absolute, or relative to the current directory) path to the respective file.
    #     Private key password is optional (needed only if key is password protected).
    #     CA certificate is optional. For all files, only PEM file format is supported.
    #     Specifying CA certificate only is obsoleted - when single entry is provided
    #     for this option, it will be interpreted as the name of a file containing bearer token.
    #     Note that the format of this command-line option prohibits use of files whose names contain
    #     ':' or '#' characters in the file name.
    # -- Provide the authentication method Falco should use to connect to the Kubernetes API.
    apiAuth: /var/run/secrets/kubernetes.io/serviceaccount/token
    ## -- Provide the URL Falco should use to connect to the Kubernetes API.
    apiUrl: "https://$(KUBERNETES_SERVICE_HOST)"
    # -- If true, only the current node (on which Falco is running) will be considered when requesting metadata of pods
    # to the API server. Disabling this option may have a performance penalty on large clusters.
    enableNodeFilter: true
```

**Comment by datan-ew** [comment]
Thanks for the response . Sure will set it to false and try , also below is our current values files , let us know if any thing needs to be adjusted on this end
        driver:
          loader:
            enabled: true
        collectors:
          docker:
            enabled: false
            socket: /var/run/docker.sock
        falco:
          outputs_queue:
            capacity: 500
          json_output: true
          http_output:
            enabled: true
            url: "http://falco-sidekick-falcosidekick:2801/"

**Comment by Andreagit97** [comment]
it seems fine!

```yaml
outputs_queue:
            capacity: 500
```
This really depends on your workload, but you should see a log like `Outputs queue out of memory. Drop event and continue on ` in case the queue is too small...if you don't see it you can keep using this value without issues

**Comment by datan-ew** [comment]
Thanks also on one pod the falco fails with an error stating the below error:

as per now we just noticed only in one pod

one pod fails with error:  Mon Oct 30 07:14:03 2023: An error occurred in an event source, forcing termination...
Events detected: 0
Rule counts by severity:
Triggered rules by rule name:
Error: error opening device /host/dev/falco0. Make sure you have root credentials and that the falco module is loaded: No such file or directory

**Comment by Andreagit97** [comment]
yes here the kernel module is not correctly loaded, probably you could try with another driver like the `modern-bpf`

**Comment by datan-ew** [comment]
is this the below option 
driver:
  enabled: true
  kind: module
# Instead of module it should be modern-bpf

**Comment by Andreagit97** [comment]
yes  this is the config I was talking about

```yaml
driver:
   enabled: true
   kind: modern-bpf
```

> also we use aws eks our node group have more than 30 nodes per one node group , so i cannot update this change to only one node as we use Argocd, is it okay to use modern-bpf for all the complete cluster.
hope it will not disturb other clusters

It should change almost nothing, the 2 drivers are equivalent, the modern probe should work out of the box on all nodes
