### ISSUE TITLE
Falcosidekick: the ServiceMonitor does not work (because its selector does not match the Service labels)

### ISSUE THREAD

**Issue by sambonbonne** [falcosecurity/charts#648]
Hello!

**Describe the bug**

Falcosidekick metrics are not scrapped.

**How to reproduce it**

Install Falco with Falcosidekick with a specific release name and enable the `ServiceMonitor`, for example: `helm install my-falco falcosecurity/falco --set "falcosidekick.serviceMonitor.enabled=true"`.

**Expected behaviour**

I hope to see some metrics scrapped by Prometheus.

**Current behaviour**

It's not working.

**Environment**

- Falco version: docker.io/falcosecurity/falco-no-driver:0.37.1
- Falco Sidekick version: docker.io/falcosecurity/falcosidekick:2.28.0
- Falco Helm chart version: 4.2.5 (latest when I'm writing this issue)
- Cloud provider or hardware configuration: information not needed
- OS: information not needed
- Kernel: information not needed
- Installation method: Kubernetes with Helm

**Additional context**

I found out that the `falcosidekick` Helm chart does not set the same `labels` for its `Service` and its `ServiceMonitor` `matchLabels`.

On my installation, the `Service` has the following labels:

```yaml
app.kubernetes.io/component: core
app.kubernetes.io/instance: my-falco # this is the problematic label
app.kubernetes.io/managed-by: Helm
app.kubernetes.io/name: falcosidekick
```

But the `ServiceMonitor` has the following `matchLabels`:

```yaml
app.kubernetes.io/component: core
app.kubernetes.io/instance: falco # not the same as the service
app.kubernetes.io/name: falcosidekick
```

We can see that the `Service` template uses `falcosidekick.labels` to set the `labels` ([see the line 8 on the template](https://github.com/falcosecurity/charts/blob/master/charts/falcosidekick/templates/service.yaml#L8)) but the `ServiceMonitor` template uses `falcosidekick.selectorLabels` to set the `matchLabels` ([see the line 24 on the template](https://github.com/falcosecurity/charts/blob/master/charts/falcosidekick/templates/servicemonitor.yaml#L24)).

So when getting the service with `kubectl get service -l <labels from matchLabels>`, there is no service listed because `app.kubernetes.io/instance` does not have the same value.
