### ISSUE TITLE
falco: allow multiple socket paths for containerd

### ISSUE THREAD

**Issue by leogr** [falcosecurity/charts#655]
**Motivation**

We already support multiple containerd socket paths in Falco :point_down: 
https://github.com/falcosecurity/libs/blob/34371e18cafa429107cf5d600bad5fd0c44718ab/userspace/libsinsp/container_engine/cri.cpp#L64-L68

This is not currently supported by the Falco chart. 

This would particularly enable k3s by default but also allow users to add multiple paths in case their use case requires that.

**Feature**

Make the `containerd.socket` accept an array of paths. For example:

https://github.com/falcosecurity/charts/blob/86536781753f7e7d0a342b42af1feb5fa158202f/charts/falco/values.yaml#L266-L270

:point_down: 

```yaml
 containerd: 
   # -- Enable ContainerD support. 
   enabled: true 
   # -- The paths to look for a ContainerD socket. The first match will be used.
   socket: [/run/containerd/containerd.sock, /run/k3s/containerd/containerd.sock]
```

**Alternatives**

The alternative would be to add a config node for each specific case (e.g., k3s). However, this is overkill and will not allow flexibility.

**Additional context**
