### ISSUE TITLE
Falcosidekick PrometheusRule query failing

### ISSUE THREAD

**Issue by ashtongraves** [falcosecurity/charts#667]
This is for the falcosidekick prometheus rules. Prometheus doesn't like the query you have for the FalcoErrorOutputEventsRateHigh alert. 

When I run this in my prometheus instance I get: `Error executing query: invalid parameter "query": 1:48: parse error: unexpected <by>`

I'm running Prometheus 2.45.0 

**How to reproduce it**

Run `rate(falcosidekick_output{status="error"}[5m]) by (destination) > 0` in prometheus

**Expected behaviour**

I expect it to run the query without error

**Environment**

I'm running via the sidekick chart bundled with the falco chart.

```
- app_version: 0.37.1
  description: Falco
  repository:
    name: falcosecurity
    url: https://falcosecurity.github.io/charts
  url: https://artifacthub.io/packages/helm/falcosecurity/falco
  version: 4.3.0
```

Prometheus 2.45.0 

**Additional context**
