### ISSUE TITLE
Dummy chart miss-use. 

### ISSUE THREAD

**Issue by jozseffarago** [falcosecurity/charts#67]
**Describe the bug**

Upon updating falco helm chart from 1.0.10, we experienced non-start problems with falco. After discussion with @leogr he noticed we are using the dummy chart in the helm stable repo, but in this case we should have an nginx in the cluster, and not falco. We had a falco deployment without the necessary mountpoints, so it failed to start up. 

**How to reproduce it**

We are using [helmfile][1] to orchestrate workload in our cluster. Additionally we have a template rendering in place(gotmpl files), but that is not relevant just note it to make the file structure more understandable. 

https://github.com/helm/charts/blob/master/stable/falco/templates/deployment.yaml#L26
```
containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
```
based on this:  https://github.com/helm/charts/blob/master/stable/falco/values.yaml#L7 We should have an nginx deployment. 

But, we have the following `helmfile.yaml`:
```
#...
releases:
- name: falcoservice
  chart: stable/falco
  version: 1.1.8
  namespace: security
  installed: true
  values:
  - values.yaml.gotmpl
#...
```

And in the `values.yaml.gotmpl` we have:
```
image:
  registry: docker.io
  repository: falcosecurity/falco
  tag: "{{ .Environment.Values.image_tag }}"
  pullPolicy: IfNotPresent
```

So the timeline is the following: 
We had 1.0.10 chart cached. Whenever we deployed it worked. We tried to upgrade to 1.8... something (does not matter), and helm pulled the new version what caused your dummy template to be used, but with our overrides for 1.0.10 -> we still deployed falco (due to the ` image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"` line), but in a corrupted manner (was not able to start up, due to missing host mounts). 

**Expected behaviour**

Dummy chart should deploy an nginx regardless of the in-place image/version pinning of the user's setup. 

**Screenshots**

N/A

**Environment**

- Falco version:
N/A
- System info:
N/A
- Cloud provider or hardware configuration:
- OS:
N/A
- Kernel:
N/A
- Installation method:
Helm chart

**Additional context**

We are using a CI/CD to deploy all of our workload, so it was not possible to see any warning about the changes if there is any. I read the README in the stable repo, but I assumed the older versions are still available from that repo and I only have to change the repo, if I want to use the latest chart with the latest falco. 
(because of this we did not upgrade to the latest version, first it seemed hard to incorporate the new repo to the CI/CD).

[1]: https://github.com/roboll/helmfile
