### ISSUE TITLE
ImagePullSecrets not consistent across Charts

### ISSUE THREAD

**Issue by rriverak** [falcosecurity/charts#673]
**Describe the bug**

If we install the latest Version of `falcosecurity/falco` Chart with a custom `ImagePullSecrets` we got a different rendering behavior from the Sidekick Subcharts.

**How to reproduce it**

Install the `falcosecurity/falco` Chart with custom ImagePullSecrets for Falco and Falcosidekick.

```
imagePullSecrets: 
  - name: my-secret

falcosidekick:
  enabled: true
  imagePullSecrets:
    - name: my-secret
```

the Manifest for the `falco` Chart itself everything looks good.

```
imagePullSecrets:
  - name: my-secret
```

but on the Sidekick Subchart we got a broken entry:

```
imagePullSecrets:
  - name: map[name:my-secret]
```

**Quickfix**
In order to generate a valid manifest, the key "name" must be removed from the imagePullSecrets list in Falcosidekick.

```
imagePullSecrets: 
  - name: my-secret

falcosidekick:
  enabled: true
  imagePullSecrets:
    - my-secret
```

**Expected behaviour**

Same interpolation logic across all charts or add at least a Note to the Docs.
