### ISSUE TITLE
Plugin k8smeta warning after creating Falco Helm chart with Kubernetes collector enabled

### ISSUE THREAD

**Issue by jfcmartins** [falcosecurity/charts#681]
**Plugin k8smeta warning after creating Falco Helm chart with Kubernetes collector enabled**

When I create Falco Helm chart with Kubernetes `k8smeta` collector, it displays the following warning:

```shell
WARNING:
It seems you are loading the following plugins [k8smeta], please make sure to install them by adding the correct reference to falcoctl.config.artifact.install.refs: [falco-rules:3 ghcr.io/falcosecurity/plugins/plugin/k8smeta:0.1.0]
```

This warning message shouldn't appear because the [Falco values.yaml](https://github.com/falcosecurity/charts/blob/falco-4.4.0/charts/falco/values.yaml#L586) has the following information:

```yaml
  # Please note that if your intention is to enrich Falco syscall logs with fields
  # such as `k8s.ns.name`, `k8s.pod.name`, and `k8s.pod.*`, you do not need to use
  # the `k8saudit` plugin. This information is automatically extracted from the
  # container runtime socket. The `k8saudit` plugin is specifically designed to
  # integrate with Kubernetes audit logs and is not required for basic enrichment
  # of syscall logs with Kubernetes-related fields.
  ```

**How to reproduce it**

Create Falco Helm chart values file:

_values.yaml_
```yaml
rbac:
  create: true

falco:
  rules_file:
    - /etc/falco/falco_rules.yaml
    - /etc/falco/falco_rules.local.yaml
    - /etc/falco/rules.d

  priority: info
  syscall_event_drops:
    actions:
      - log

  grpc:
    enabled: true
  grpc_output:
    enabled: true

  load_plugins: []

driver:
  enabled: true
  kind: modern_ebpf
  modernEbpf:
    bufSizePreset: 5

collectors:
  enabled: true
  kubernetes:
    enabled: true

controller:
  kind: daemonset

falcosidekick:
  enabled: true
  config:
    debug: true
    slack:
      outputformat: "fields"
      webhookurl: "<redacted>"
```

Then apply the Helm chart:

```shell

helm upgrade -i falco falcosecurity/falco \
  -f values.yaml \
  --version 4.4.0
```

**Expected behaviour**

Helm chart warning shouldn't appear for this use case.

**Screenshots**

<img width="665" alt="image" src="https://github.com/falcosecurity/charts/assets/76965647/cb44bbf9-8a49-4697-8803-1ecccd1c42ef">

**Environment**

- Falco version: 0.38.0
- System info: Linux version 5.10.198-187.748.amzn2.x86_64(GCC) 10.5.0 20230707 (Red Hat 10.5.0-1), GNU ld version 2.35.2-9.amzn2.0.1)
- Cloud provider or hardware configuration: AWS EKS
- OS: Debian GNU/Linux 12 (bookworm)
- Kernel: Linux falco-gs4rr SMP Tue Oct 24 19:49:54 UTC 2023 x86_64 GNU/Linux
- Installation method: Kubernetes, Helm

Am I missing something? I really appreciate any help you can provide.
