### ISSUE TITLE
Falco Sidekick UI Ingress not functional

### ISSUE THREAD

**Issue by benglewis** [falcosecurity/charts#704]
**Describe the bug**

When using the Helm chart to use Falco Sidekick UI with an Ingress, the resulting endpoint results in 404 on all resource requests.

**How to reproduce it**

Run Helm chart with Falco Sidekick UI with an Ingress on GCP. Please see: https://github.com/falcosecurity/charts/issues/402#issuecomment-2198452925

**Expected behaviour**

Falco Sidekick UI should work on the address indicated by the Ingress.

**Screenshots**

Please see:
https://github.com/falcosecurity/charts/issues/402#issuecomment-2212425209

**Environment**

- Falco version:
0.38.1
- System info:
```
Sun Jul  7 15:33:38 2024: Using deprecated config key 'rules_file' (singular form). Please use new 'rules_files' config key (plural form).
Sun Jul  7 15:33:38 2024: Falco version: 0.38.1 (x86_64)
Sun Jul  7 15:33:38 2024: Falco initialized with configuration files:
Sun Jul  7 15:33:38 2024:    /etc/falco/falco.yaml
Sun Jul  7 15:33:38 2024: System info: Linux version 6.1.85+ (builder@faf02fc191fd) (Chromium OS 16.0_pre484197_p20230405-r10 clang version 16.0.0 (/var/tmp/portage/sys-devel/llvm-16.0_pre484197_p20230405-r10/work/llvm-16.0_pre484197_p20230405/clang 2916b99182752b1aece8cc4479d8d6a20b5e02da), LLD 16.0.0) #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
Sun Jul  7 15:33:38 2024: Loading rules from file /etc/falco/falco_rules.yaml
{
  "machine": "x86_64",
  "nodename": "falco-pqft2",
  "release": "6.1.85+",
  "sysname": "Linux",
  "version": "#1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024"
}
```
- Cloud provider or hardware configuration:
GCP GKE
- OS:
Node is running on GCP Container-Optimized OS. Falco image seems to be Ubuntu based-based.
- Kernel:
6.1.85+
- Installation method:
Helm chart via Pulumi.

**Additional context**

N/A

**Comment by Issif** [comment]
Can you try to set the `pathType` to `Prefix` to check if it works better please.

```yaml
falcosidekick: 
  enabled: true
  webui: 
    enabled: true
    user: "REDACTED:REDACTED"
    service: 
      type: "NodePort"
      annotations: 
        cloud.google.com/neg: "{\"ingress\": true}"
        cloud.google.com/app-protocols: "{\"http\": \"HTTP\"}"
    ingress: 
      enabled: true
      annotations: 
        kubernetes.io/ingress.class: "gce-internal"
        kubernetes.io/ingress.allow-http: true
        networking.gke.io/v1beta1.FrontendConfig: "frontend-config"
      hosts: 
        - host: "falcosidekick-ui.falco.mvp.dev.hirundo.io"
          paths: 
          - path: "/
            pathType: Prefix
```
