### ISSUE TITLE
falcosidekick config.existingSecret causing conflicts in helm chart v0.8.2

### ISSUE THREAD

**Issue by flickers** [falcosecurity/charts#713]
**Describe the bug**
In falcosidekick helm chart v0.8.2 when using config.existingSecret the falcosidekick default secret is also loaded into env causing conflicts and crashLoops in falcosidekick

**How to reproduce it**
Uside config.existingSecret that loads key:value pairs that also exists in the default falcosidekick secret

**Expected behaviour**
When using config.existingSecret falcosidekick helm chart should only use that secret and not the default one created by the helm chart.

**Screenshots**
This is most likely caused by this change
[https://github.com/falcosecurity/charts/commit/f8205957df7b0a6b7fde6a83fe16d6bc8f0e24be#diff-847ce2ce19ea600eb056e59[…]76c4c12fe8d5b689f4768R98-R104](https://github.com/falcosecurity/charts/commit/f8205957df7b0a6b7fde6a83fe16d6bc8f0e24be#diff-847ce2ce19ea600eb056e592c0e0f527cd45db0d39e76c4c12fe8d5b689f4768R98-R104)

Helm chart v0.7.22 (uses either existingSecret **OR** default created by helm chart)
```yaml
            - secretRef:
                {{- if .Values.config.existingSecret }}
                name: {{ .Values.config.existingSecret }}
                {{- else }}
                name: {{ include "falcosidekick.fullname" . }}
                {{- end }}
```

Helm chart v0.8.2 (always load the default from helm chart **AND** existingSecret if used)
```yaml
            - secretRef:
                name: {{ include "falcosidekick.fullname" . }}
            {{- if .Values.config.existingSecret }}
            - secretRef:
                name: {{ .Values.config.existingSecret }}
            {{- end }}
```

**Environment**

- Falco version:

- System info: 

- Cloud provider or hardware configuration: AWS EKS
- OS: Linux

- Kernel:

- Installation method: Kubernetes Helm

**Additional context**
Slack discussion: https://kubernetes.slack.com/archives/CMWH3EH32/p1720704347316519
