### ISSUE TITLE
Value of `OTLP_TRACES_PROTOCOL` is set to the `endpoint`

### ISSUE THREAD

**Issue by carlreid** [falcosecurity/charts#741]
**Describe the bug**

Although the README describes the following:
> config.otlp.traces.protocol | string | `""` | OTLP protocol http/json, http/protobuf, grpc (default: "" which uses SDK default: http/json) |

The value of the `OTLP_TRACES_PROTOCOL` [is being set](https://github.com/falcosecurity/charts/blob/4e87255cef4fdaadfe126429d9186302b527b0c3/charts/falcosidekick/templates/secrets.yaml#L466) to the same value as `.Values.config.otlp.traces.endpoint`.

**How to reproduce it**

Try set config as;
```yaml
  falcosidekick:
    enabled: true
    fullfqdn: true
    webui:
      enabled: true
      disableauth: true
      replicaCount: 1
    config:
      otlp:
        traces:
          endpoint: "http://my-collector-endpoint:4318/v1/traces"
          protocol: "http/json"
          checkcert: false
```

Then observe `protocol` is not passed.

**Expected behaviour**

That the `OTLP_TRACES_PROTOCOL` is being set to the `config.otlp.traces.protocol` value.
