### ISSUE TITLE
Add PodMonitoring support to falco-exporter

### ISSUE THREAD

**Issue by bzaleski578** [falcosecurity/charts#796]
**Motivation**

Use falco-exporter with GCP's Managed Service for Prometheus

Currently Falco uses ServiceMonitor object from the API monitoring.coreos.com/v1 that works with the Prometheus-operator 
That object is not compatible with GCP's Managed Service for Prometheus.

**Feature**

Add support for PodMonitoring (API: monitoring.googleapis.com/v1)

**Additional context**

In my GKE I am using the below two helmcharts to deploy Falco and store its alerts in Prometheus:
* https://github.com/falcosecurity/charts/falco
* https://github.com/falcosecurity/charts/falco-exporter

I am also using GCP's Managed Service for Prometheus, 
To make the two work together I had to manually add my PodMonitor object to the falco-exporter chart. It would be tremendous to be able to simply choose which object I want to use from my values.yaml..

**Comment by alacuku** [comment]
Hi @bzaleski578, `falco-exporter` will be deprecated soon: https://github.com/falcosecurity/evolution/issues/420.

It would be best if you used the metrics exposed by Falco itself.

**Comment by bzaleski578** [comment]
Hi @alacuku 

Thanks for your timely response.

Perhaps this request is still valid though, since the Falco helmchart does not support PodMonitoring either?

**Comment by alacuku** [comment]
yes, we should support PodMonitoring in the Falco chart.

But it's not clear to me what you mean by this:

> Add support for PodMonitoring (API: monitoring.googleapis.com/v1)

**Comment by bzaleski578** [comment]
Both the objects serve the same purpose - scrape Prometheus metrics from a given endpoint. However, they come from different APIs and are therefore consumed by different services.

ServiceMonitor (and PodMonitor to be precise) are provided from the [Prometheus-operator](https://github.com/prometheus-operator/prometheus-operator). So the Prometheus-operator must be deployed in your cluster in order to scrape metrics from ServiceMonitor (or PodMonitor).

In GCP (I don't know how about other clouds) there is an alternative for running the Prometheus-operator. It is called [GCP Managed Service for Prometheus](https://cloud.google.com/stackdriver/docs/managed-prometheus) and is provided by the cloud vendor. The advantage of using it is that there is no need to deploy custom Prometheus-operator thus reducing maintenance overhead. This GCP Managed Service for Prometheus uses PodMonitoring object for scraping metrics. It cannot use the ServiceMonitor objects instead.

Note: I have seen posts on Internet saying that ServiceMonitor and PodMonitoring are actually compatible and that the compatibility can be achieved by certain annotation(s). I haven't manage to achieve that though, so I am assuming that the objects are not in fact compatible.

The way I see it working is something along these lines:

1. Add PodMonitoring definition in `charts/falco/templates.podMonitoring.yaml`

```yaml
{{- if .Values.podMonitoring.enabled }}
apiVersion: monitoring.googleapis.com/v1
kind: PodMonitoring
metadata:
  name: {{ include "falco.fullname" . }}
  labels:
    {{- include "falco.labels" . | nindent 4 }}
    {{- range $key, $value := .Values.podMonitoring.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "falco.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: {{ .Values.podMonitoring.port }}
    interval: {{ .Values.podMonitoring.interval }}
    path: {{ .Values.podMonitoring.path | quote }}
{{- end }}
```

2. Now either (PodMonitoring or ServiceAccount) can be used based on your custom `values.yaml`:

```yaml
serviceMonitor:
  create: false

podMonitoring:
  enabled: true
  interval: 180s
  path: /metrics
```

Most likely more changes would be required in the helmchart, this is only a simplistic example of a DevOps' perspective
