### ISSUE TITLE
Missing Ports definition in podTemplate

### ISSUE THREAD

**Issue by sylvesterdamgaard** [falcosecurity/charts#812]
**Describe the bug**

The issue arises when the Falco webserver is enabled without explicitly defining the ports section in the container specification.  
This prevents other services, such as Grafana Alloy, from connecting and scraping metrics.   
Although access to the service is granted, metrics scraping requires either a headless service or explicitly exposed ports. The current setup does not fulfill this requirement, leading to operational issues.

**How to reproduce it**

Deploy falco with webserver enabled, metrics enabled and prometheus_metrics_enabled enabled.
```yaml
falco:
  webserver:
    prometheus_metrics_enabled: true
metrics:
  enabled: true
```
```bash
helm upgrade --install falco falcosecurity/falco \
  --namespace falco \
  --create-namespace \
  --set falco.webserver.prometheus_metrics_enabled=true \
  --set metrics.enabled=true
```

**Expected behaviour**

I expect to have ports: definition in the falco container specs.
[charts/falco/templates/pod-template.tpl](https://github.com/falcosecurity/charts/blob/master/charts/falco/templates/pod-template.tpl)
```
ports:
- containerPort: 8765
  name: metrics
  protocol: TCP
```

**Environment**

- Falco chart version:
[4.17.0](https://github.com/falcosecurity/charts/releases/tag/falco-4.17.0)
- Installation method:
Helm chart
