### ISSUE TITLE
Falcosidekick - missing configmap when externalredis is enabled

### ISSUE THREAD

**Issue by Aliloya-eng** [falcosecurity/charts#856]
**Describe the bug**

I am trying to set up falco+falcosidekick with web-ui and externalRedis enabled.

In `deployment-ui`, the initContainer `wait-redis` is expecting the volumeMount with the volume `scripts` [LINK](https://github.com/falcosecurity/charts/blob/master/charts/falcosidekick/templates/deployment-ui.yaml#L74).
This volume is of type configMap and should be available under `configmap-ui` [LINK](https://github.com/falcosecurity/charts/blob/master/charts/falcosidekick/templates/configmap-ui.yaml). This is always the case (for both cases where either redis or externalRedis is enabled).
However, we see that this configMap will be missing in the case of externalRedis bevause `.Values.webui.redis.enabled` is required to be `true` [LINK](https://github.com/falcosecurity/charts/blob/master/charts/falcosidekick/templates/configmap-ui.yaml#L1).

This issue is failing the release/deployment with the following event:

![Image](https://github.com/user-attachments/assets/6b3fc031-0861-421b-8fe3-3c977f8e0bed)

**Suggested fix**
Remove the second condition from the first condition in `configmap-ui` as follows
```
--- a/charts/falcosidekick/templates/configmap-ui.yaml
+++ b/charts/falcosidekick/templates/configmap-ui.yaml
@@ -1,4 +1,4 @@
-{{- if and (.Values.webui.enabled) (.Values.webui.redis.enabled) -}}
+{{- if .Values.webui.enabled -}}
 ---
 apiVersion: v1
 kind: ConfigMap
```

**How to reproduce it**
Install Falco with the following values file:
```
falcosidekick:
    enabled: true
    webui:
        enabled: true
        redis:
            enabled: false
        externalRedis:
            enabled: true
            url: URL
            password: PASSWORD
```

**Expected behaviour**

I expect falco deployment (with falcosidekick-webui+externalredis) to be successful.

**Environment**

- Falco version:
`Falco version: 0.40.0 (x86_64)` 
- Installation method:
`helm install falco -f values.yml --namespace falco --create-namespace falcosecurity/falco`
