### ISSUE TITLE
Falcos Dashboard Priorities mapping wrong

### ISSUE THREAD

**Issue by rriverak** [falcosecurity/charts#865]
**Describe the bug**

The `Priorities` Pie-Chart in Falcos Dashboard not working as expected.

**How to reproduce it**

Install the `falco` Chart with the following values:
```
metrics:
  enabled: true

grafana:
  dashboards:
    enabled: true
    configMaps:
      falco:
        name: falco-grafana-dashboard
        namespace: "monitoring"
        folder: "infrastructure"

serviceMonitor:
  create: true
```
Take a look at the Dashboard.

**Expected behaviour**

See the correct `Priorities` Mapping for the Pie-Chart.

You can see the `Priorities` Enum from Falco:
https://github.com/falcosecurity/falco/blob/7badc31cb17e3b3f896bc48166614252bde47e5c/userspace/falco/schema.proto#L24

but the mapping of the pie chart is not the same. It looks twisted.

https://github.com/falcosecurity/charts/blob/master/charts/falco/dashboards/falco-dashboard.json#L492C1-L556C1

**Environment**

- Falco/Chart version: 4.21.3
- Cloud provider or hardware configuration: OpenStack
- OS: Ubuntu / Kubernetes
- Kernel: 6.8.0-58-generic
- Installation method: Helm
